#!/bin/sh

# Grab all the latest files to do a commit

cp $HOME/.homeassistant/packages/appliances/maverick.yaml packages/
cp $HOME/.homeassistant/lovelace/maverick.yaml lovelace/
cp $HOME/.homeassistant/lovelace/bbq-tasks.yaml lovelace/

cp $HOME/.homeassistant/packages/appliances/oven.yaml packages/
cp $HOME/.homeassistant/lovelace/oven.yaml lovelace/

scp orangepi:/home/denny/bin/denny-rtl2mqtt.py bin/
scp orangepi:/home/denny/bin/config.py bin/
