homeassistant:

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################
group:

  oven:
    name: Oven
    entities:
      - sensor.oven_probe
      - sensor.oven_food_probe
      - input_number.oven_target_temp
      - input_number.oven_food_target_temp
      - input_text.oven_food_name
      - binary_sensor.oven_on
      - binary_sensor.oven_temp_achieved
      - binary_sensor.oven_food_temp_achieved


#################################################################
#                                                               #
#                        Binary Sensors                         #
#                                                               #
#################################################################
binary_sensor:

  - platform: template
    sensors:
      oven_on:
        friendly_name: "Oven Probe is On"
        entity_id: sensor.time
        device_class: connectivity
        value_template: >-
          {{ (as_timestamp(utcnow()) - as_timestamp(state_attr('sensor.oven_probe','time'))) < 300 }}

      oven_temp_achieved:
        friendly_name: Oven Temp Achieved
        entity_id: sensor.oven_probe
        device_class: heat
        delay_off:
          minutes: 10
        value_template: >-
          {{ (states('sensor.oven_probe')|float > states('input_number.oven_target_temp')|float) and (states('binary_sensor.oven_on') == 'on') }}

      oven_food_temp_achieved:
        friendly_name: Oven Food Temp Achieved
        entity_id: sensor.oven_food_probe
        device_class: heat
        value_template: >-
          {{ (states('sensor.oven_food_probe')|float > states('input_number.oven_food_target_temp')|float) and (states('binary_sensor.oven_on') == 'on') }}


#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################
#                           RTL2MQTT                            #
#  rtl_433_cmd = "/usr/local/bin/rtl_433 -f 433.776m -F json"   #
#                                                               #
#################################################################
sensor:

  - platform: mqtt
    name: Oven Food Probe
    unique_id: oven_food_probe_34088
    unit_of_measurement: '°C'
    state_topic: "sensors/rtl_433/Maverick-ET73x/34088/STATE"
    value_template: "{{ value_json.temperature2_C }}"
    json_attributes_topic: "sensors/rtl_433/Maverick-ET73x/34088/STATE"

  - platform: mqtt
    name: Oven Probe
    unique_id: oven_probe_34088
    unit_of_measurement: '°C'
    state_topic: "sensors/rtl_433/Maverick-ET73x/34088/STATE"
    value_template: "{{ value_json.temperature1_C }}"
    json_attributes_topic: "sensors/rtl_433/Maverick-ET73x/34088/STATE"


#################################################################
#                                                               #
#                         Input Number                          #
#                                                               #
#################################################################
input_number:

  oven_target_temp:
    name: Oven Target Temperature
    initial: 350
    min: 100
    max: 600
    mode: slider

  oven_food_target_temp:
    name: Oven Food Target Temperature
    initial: 165
    min: 100
    max: 600
    mode: slider

#################################################################
#                                                               #
#                          Input Text                           #
#                                                               #
#################################################################
input_text:
  oven_food_name:
    name: Oven Food
    initial: Grub
